### ISSUE TITLE
Coverage workflow: pulp-rs cargo build fails on macOS CI runner (ring crate / TargetConditionals.h)

### ISSUE THREAD

**Issue by danielraffel** [Generous-Corp/pulp#785]
## Summary

PR #778 (Phase 8 PR #1, CMake bridge for the Rust CLI) added the experimental Rust binary to the CMake build graph. The bridge guards against missing cargo via PULP_SKIP_RUST_CLI / PULP_BUILD_RUST_CLI / find_program — but it doesn't tolerate a cargo build that starts and then fails.

On the macOS coverage workflow runner, cargo IS on PATH, so the bridge proceeds — and \`cargo build\` fails because a transitive dep (\`ring v0.17.14\`) can't find \`TargetConditionals.h\` from the active Xcode SDK:

\`\`\`
warning: ring@0.17.14: /Users/runner/.cargo/registry/.../ring-core/base.h:33:10: fatal error: 'TargetConditionals.h' file not found
warning: ring@0.17.14: 1 error generated.
error: failed to run custom build command for \`ring v0.17.14\`
  process didn't exit successfully: \`/Users/runner/work/pulp/pulp/build-coverage/.../build-script-build\` (exit status: 1)
\`\`\`

This kills the whole \`cmake --build build-coverage\` invocation, which then can't generate \`coverage.cobertura.xml\`, which fails the macOS coverage job.

Root cause: macOS coverage runs use \`-DCMAKE_OSX_SYSROOT\` (or similar) plumbing for Apple Clang, and that sysroot doesn't include the iOS/macOS conditionals headers that ring's build script wants. The Rust toolchain on the same machine has its own SDK detection that disagrees.

## Why it's not in PR #778's scope

PR #778's CMake bridge is correct in design — when cargo is available it builds the Rust binary, when not it fails-soft. The failure mode "cargo present but build fails" is the new edge case introduced by PR #778. Before #778, this couldn't happen because there was no cargo build in the CMake graph.

## Suggested fixes (in priority order)

1. **Set \`PULP_SKIP_RUST_CLI=1\` in the macOS coverage job** (lowest risk, most surgical):

   \`\`\`yaml
   # .github/workflows/coverage.yml — coverage-macos job
   - name: Run coverage suite
     env:
       PULP_SKIP_RUST_CLI: '1'  # cli-rust coverage runs in its own job
     run: scripts/run_coverage.sh
   \`\`\`

   The cli-rust coverage tier (planned for PR #2 / #783) will run via cargo-llvm-cov in its own job, so the C++ coverage job doesn't need the Rust binary.

2. **Same for sanitizer jobs** — same pattern, same justification.

3. **(longer-term)** investigate why ring fails: maybe the runner's Xcode CommandLineTools install is incomplete; OR pin ring through a Cargo.toml feature that doesn't trigger the C-build path; OR use rustls without ring entirely.

## Severity

P2 — Coverage and sanitizer macOS jobs are advisory (don't gate merge per the workflow's own comment: "Non-blocking coverage artifact. Informational only; no merge gate."). Linux + Windows coverage are unaffected (they tolerate the same path differently). PR #778 itself can land with the macOS coverage in red — the cli-rust coverage tier will be added separately under #783.

## Refs

- Caused by: PR #778 (Phase 8 PR #1)
- Affects: \`Coverage report (macOS, Clang)\`, \`AddressSanitizer (macOS ARM64)\`, \`UndefinedBehaviorSanitizer (macOS ARM64)\`
- Refs: #767, #686
